### ISSUE TITLE
Implement basic method syntax

### ISSUE THREAD

**Issue by kevin1** [jeb2239/Linq4Cpp#2]
Please check off methods as they are implemented (including any overrides described in [Microsoft's LINQ documentation](https://msdn.microsoft.com/en-us/library/vstudio/system.linq.enumerable%28v=vs.100%29.aspx))
- [x] select
- [x] where
- [x] all
- [x] any
- [x] contains
- [x] concat
- [x] orderby/thenby
- [x] reverse
- [x] average
- [x] count
- [x] max
- [x] min
- [x] sum
- [x] elementat
- [x] first
- [x] last
- [x] single
- [x] skip
- [x] take

**Comment by jeb2239** [comment]
what is the status of concat?
