### ISSUE TITLE
Implement performance testing

### ISSUE THREAD

**Issue by kevin1** [jeb2239/Linq4Cpp#5]
Bjarne suggested that we use some large, "standard" data set such as a list of cities in the US. List of cities makes sense, because then you could query based on name, population, lat/long, country, etc.
- [x] CINQ filtering and the same filter using only standard library features
- [ ] CINQ and LINQ for C++
- [x] CINQ with and without lazy deletion
- [ ] Running the same filter in CINQ method syntax and CINQ query syntax
- [x] Just for fun, also compare CINQ method syntax, C# method syntax (Microsoft CLR), and C# method syntax (Mono ahead-of-time compilation)

**Comment by jeb2239** [comment]
So we are going to give the lazy deletion a shot?

**Comment by kevin1** [comment]
If we have time or if the performance is really atrocious. The other tests are more important imo.

**Comment by kevin1** [comment]
fixed in d59a600
